Add deactivate functionality to dreamblocks
EverestAPI/Everest pull request #170
Opened 2020-05-18 06:20 UTC by coloursofnoise

Reuses the same animation as activation.
[Video](https://discordapp.com/channels/403698615446536203/429775320720211968/711491773708632135)

2020-05-18 14:35 UTC, 0x0ade requested changes
Code styling is off (see comment in the trigger; lack of spacing in DeactivateNoRoutine and Deactivate in DreamBlock itself), but looks good otherwise.

2020-05-18 14:35 UTC, 0x0ade commented on Celeste.Mod.mm/Mod/Entities/ActivateDreamBlocksTrigger.cs
> +            else if (deactivate && level.Session.Inventory.DreamDash) {
```suggestion
            } else if (deactivate && level.Session.Inventory.DreamDash) {
```

2020-05-18 14:35 UTC, 0x0ade commented on Celeste.Mod.mm/Patches/DreamBlock.cs
> +                shaker = new Shaker(true, delegate (Vector2 t) {
```suggestion
                shaker = new Shaker(true, t => {
```

2020-05-22 01:15 UTC, coloursofnoise commented
Feel free to give feedback on the "fast" animation.

2020-05-29 20:13 UTC, 0x0ade approved these changes

2020-06-01 11:23 UTC, merged