Unused code cleanup & Discord Rich Presence toggle
EverestAPI/Everest pull request #277
Opened 2021-02-02 20:46 UTC by Lollyde

2021-02-02 21:45 UTC, 0x0ade requested changes

2021-02-02 21:45 UTC, 0x0ade commented on Celeste.Mod.mm/Mod/Core/CoreModuleSettings.cs
> +            }
There's no protection against this being set to true / false consecutively multiple times. Either implement something in Everest.Discord to take this into account, or (cheaper) `if (value != disableDiscordRichPresence) { ... }`

2021-02-02 22:08 UTC, Lollyde commented on Celeste.Mod.mm/Mod/Core/CoreModuleSettings.cs
> +            }
added a check to skip the initialization/shutdown if Everest.Discord is already initialized/shut down 👍

2021-02-02 22:12 UTC, Lollyde commented
actually, this commit breaks initializing Discord Rich Presence somehow - do not merge yet

2021-02-03 11:59 UTC, 0x0ade approved these changes

2021-02-03 11:59 UTC, 0x0ade commented on Celeste.Mod.mm/Mod/Core/CoreModuleSettings.cs
> +                    return;
This check should ideally be moved to `Everest.Discord` as there *could* be f.e. a mod calling `.Initialize()` without first checking `.Initialized` - it is fine as is though.

2021-02-03 17:02 UTC, merged