Entity PreUpdate and PostUpdate implemented through Components.
EverestAPI/Everest pull request #412
Opened 2022-01-24 01:49 UTC by Viv-0

This acts to replace https://github.com/EverestAPI/Everest/pull/406 by implementing PreUpdate and PostUpdate as interfaces for Components to inherit. This has also made the changes requested in that PR with respect to anything that remains between the two versions.
This has been tested with a test mod and does work. Unknown benchmarking difference compared to the event option.

2022-01-30 05:41 UTC, coloursofnoise requested changes
Rather than an interface, might it be better to just add a `PostUpdate` and `PreUpdate` Component that accepts a delegate? (Or just one component that accepts both, then you could retrieve the list once for PreUpdate and reuse it in PostUpdate?)

Also, should Pre/PostUpdate be called when the entity isn't `Active`? It seems odd to me that they would be called when `Update` isn't.

2022-01-30 05:41 UTC, coloursofnoise commented on Celeste.Mod.mm/MonoModRules.cs
> +            cursor.GotoNext(MoveType.Before, instr => instr.MatchBr(out loopBranchLabel));
Why is `loopBranchLabel` defined if it doesn't get used? Why not just jump straight to `Entity.Update`?

2022-01-30 05:41 UTC, coloursofnoise commented on Celeste.Mod.mm/MonoModRules.cs
> +            cursor.Emit(OpCodes.Brfalse, activeBranchLabel);
If Pre/PostUpdate will be called regardless of the entity being `Active`, there should be no need to replace the branch instructions here since it does not change.

2022-02-01 23:30 UTC, Viv-0 commented
> Also, should Pre/PostUpdate be called when the entity isn't `Active`? It seems odd to me that they would be called when `Update` isn't.
This is to enable certain objects to toggle on and off the object even if Active is already false, see Flag-Toggled Containers from EeveeHelper as an example of the specific use case.

2022-02-01 23:31 UTC, Viv-0 commented on Celeste.Mod.mm/MonoModRules.cs
> +            cursor.GotoNext(MoveType.Before, instr => instr.MatchBr(out loopBranchLabel));
I'll test removing it

2022-02-03 00:12 UTC, Viv-0 commented
Updated MonoModRules patch as well as replaced interfaces with abstract Component inherited classes
abstract version not tested but given that the method should clearly work I didn't think it prudent to do the test here, given that the same function effectively worked last time. ILSpy code reviewed and does patch as expected.

2022-02-03 02:09 UTC, DemoJameson requested changes
I think patch `ComponentList.Update` is better, so that you don't have to iterate components twice

2022-02-03 02:09 UTC, DemoJameson commented on Celeste.Mod.mm/Patches/Monocle/Entity.cs
> +            foreach (PreUpdateComponent puc in Components) {
Cause 'System.InvalidCastException' when casting from Monocle.Component to Celeste.Mod.Entities.PreUpdateComponent

2022-02-03 02:09 UTC, DemoJameson commented on Celeste.Mod.mm/Patches/Monocle/Entity.cs
> +            foreach (PostUpdateComponent puc in Components) {
Cause 'System.InvalidCastException' when casting from Monocle.Component to Celeste.Mod.Entities.PostUpdateComponent

2022-02-03 02:12 UTC, DemoJameson requested changes
`IPreUpdateComponent.cs` should be renamed to `PreUpdateComponent.cs`

2022-02-03 04:55 UTC, DemoJameson commented
> Updated MonoModRules patch as well as replaced interfaces with abstract Component inherited classes
> 
> abstract version not tested but given that the method should clearly work I didn't think it prudent to do the test here, given that the same function effectively worked last time. ILSpy code reviewed and does patch as expected.

Because you use two abstract classes, there is no way we can use two methods in the same component at the same time, which I think is unreasonable. You can merge into one abstract class or switch back to interface, but I think it's better to add methods directly in the component

2022-02-08 00:47 UTC, Viv-0 commented
> > Updated MonoModRules patch as well as replaced interfaces with abstract Component inherited classes
> > abstract version not tested but given that the method should clearly work I didn't think it prudent to do the test here, given that the same function effectively worked last time. ILSpy code reviewed and does patch as expected.
> 
> Because you use two abstract classes, there is no way we can use two methods in the same component at the same time, which I think is unreasonable. You can merge them into one abstract class, but I think it's better to add methods directly in the component

My point of concern there is more of "if every component is running two extra methods every entity every frame that equates to a lot of lag. Furthermore, if not a lot of Components *need* that behavior then I wouldn't want to slow down the game massively over something that isn't going to be used much compared to not being used, hence the abstract class

2022-02-08 05:45 UTC, DemoJameson commented
then I think an interface would be more appropriate than two abstract classes

2022-02-08 20:44 UTC, Viv-0 commented
> then I think two interfaces would be more appropriate than two abstract classes
> since a class can implement multiple interfaces but not inherit multiple classes

This waa my original idea but colours recommended otherwise. I can re-implement it though, if thatll move the ball forward on this

2022-02-11 01:25 UTC, DemoJameson approved these changes

2022-02-11 03:54 UTC, coloursofnoise approved these changes

2022-02-15 19:18 UTC, Viv-0 commented
Please dont merge this yet. I'm gonna make one small optimization, changing Action to Action<Entity> since storing it as an argument can reduce lag at high numbers of actions

2022-02-24 17:16 UTC, 0x0ade requested changes
LGTM besides the small style nitpicks. Can merge as is if necessary and fix afterwards tho.

I'm not sure if I'm a fan of the "preceder" and "finalizer" terminology, but the component fields are perfectly understandable (pre and post), and that terminology is only used behind the scenes anyways.

2022-02-24 17:16 UTC, 0x0ade commented on Celeste.Mod.mm/Patches/Monocle/Entity.cs
> +                if(_component is UpdateWrappingComponent component)
```suggestion
                if (_component is UpdateWrappingComponent component)
```

2022-02-24 17:16 UTC, 0x0ade commented on Celeste.Mod.mm/MonoModRules.cs
> +            cursor.GotoNext(MoveType.AfterLabel, instr=>instr.MatchLdloca(0), i2 => i2.MatchCall(out MethodReference method) && method.Name == "MoveNext");
```suggestion
            cursor.GotoNext(MoveType.AfterLabel, instr => instr.MatchLdloca(0), i2 => i2.MatchCall(out MethodReference method) && method.Name == "MoveNext");
```

2022-02-28 02:58 UTC, Viv-0 commented
> I'm not sure if I'm a fan of the "preceder" and "finalizer" terminology
I can change that to PreUpdate and PostUpdate since that makes sense in both contexts. EntityList.Update runs Entity.Update, Entity.PreUpdate can run PreUpdate

2022-03-01 08:39 UTC, 0x0ade approved these changes

2022-03-01 08:39 UTC, merged