Implement parsing Backdrop Tags as a comma separated list
EverestAPI/Everest pull request #418
Opened 2022-02-13 22:07 UTC by JaThePlayer

Closes #417 
Parses Backdrop Tags as a comma separated list. Since `Backdrop.Tags` is `HashSet<string>` already, this is really simple to implement. This is really beneficial for any sort of advanced backdrop manipulation, like what Windowpane Helper does (in fact, that mod manually implements this exact change)

This is the change in `MapData.ParseBackdrop`:
```cs
if (child.HasAttr("tag")) {
    //backdrop.Tags.Add(child.Attr("tag"));
    MapData.ParseTags(child, backdrop);
}
if (above != null && above.HasAttr("tag")) {
    //backdrop.Tags.Add(above.Attr("tag"));
    MapData.ParseTags(above, backdrop);
}
```

2022-02-14 02:07 UTC, WEGFan commented
Everest patches should fail hard wherever possible, the code should add checks for instruction matches like this.

```diff
    // Allow multiple comma separated tags
+   int matches = 0;
    OpCode argOpcode = OpCodes.Ldarg_1;
    while (cursor.TryGotoNext(MoveType.After, instr => instr.MatchLdstr("tag"), instr => instr.MatchCallvirt("Celeste.BinaryPacker/Element", "HasAttr"))) {
        cursor.Index++; // move past the branch
        cursor.RemoveRange(8); // remove old code
    
        cursor.Emit(argOpcode); // child
        cursor.Emit(OpCodes.Ldloc_0); // backdrop
    
        cursor.Emit(OpCodes.Call, m_ParseTags);
    
        argOpcode = OpCodes.Ldarg_2;
+       matches++;
    }
+   if (matches != 2) {
+       throw new Exception("Incorrect number of matches for HasAttr(\"tag\")");
+   }
```

2022-02-14 02:08 UTC, WEGFan requested changes
Everest patches should fail hard wherever possible, the code should add checks for instruction matches like this.

```diff
    // Allow multiple comma separated tags
+   int matches = 0;
    OpCode argOpcode = OpCodes.Ldarg_1;
    while (cursor.TryGotoNext(MoveType.After, instr => instr.MatchLdstr("tag"), instr => instr.MatchCallvirt("Celeste.BinaryPacker/Element", "HasAttr"))) {
        cursor.Index++; // move past the branch
        cursor.RemoveRange(8); // remove old code
    
        cursor.Emit(argOpcode); // child
        cursor.Emit(OpCodes.Ldloc_0); // backdrop
    
        cursor.Emit(OpCodes.Call, m_ParseTags);
    
        argOpcode = OpCodes.Ldarg_2;
+       matches++;
    }
+   if (matches != 2) {
+       throw new Exception("Incorrect number of matches for HasAttr(\"tag\")");
+   }
```

2022-02-22 04:01 UTC, WEGFan approved these changes
Ideally `MapData.ParseTags` should be private but I guess that's not a big problem, and it will require us using reflections if we want to access that in mods 😅

2022-02-24 17:09 UTC, 0x0ade commented on Celeste.Mod.mm/MonoModRules.cs
> +                    _ => throw new Exception($"Too many matches for HasAttr(\"tag\"): {matches}")
`matches` should always be 2 at that point.

2022-02-24 17:10 UTC, 0x0ade commented on Celeste.Mod.mm/Patches/MapData.cs
> +        public static void ParseTags(BinaryPacker.Element child, Backdrop backdrop) {
I agree with WEGFan that this method should be private, and personally don't see why a mod would ever want to use this. But on the other hand, there should be no harm in keeping this public.

2022-02-24 17:11 UTC, merged