Implement Custom Backdrops through custom attribute
EverestAPI/Everest pull request #468
Opened 2022-07-05 01:07 UTC by catapillie

This adds a `CustomBackdropAttribute` attribute class under the `Celeste.Mod.Backdrops` namespace. You can use it instead of subscribing to an everest provides when custom backdrops are loaded. This makes registering custom backdrops much easier, and could have its own section in the wiki, for those who are looking for implementing their own backdrops.

When an Everest module is registered, after looking for custom entities and events, it will, in the same manner, look for custom backdrops. IDs are associated with a loader delegate, and stored in a dictionary in `patch_MapData`.

For loading custom backdrops, the `patch_MapData.LoadCustomBackdrop` will now:
* attempt to load any custom backdrop through the `Everest.Events.Level.OnLoadBackdrop` event, which thus have priority over any other custom backdrop
* search for a matching ID in the dictionary that contains the registered custom backdrops, and invoke the associated loader delegate if found
* do the rest, notably, perform the custom loading the of `rain` backdrop, or return `null`.

Example:
```cs
[CustomBackdrop("CustomBackdrops/Test")]
public class CustomBackdrop : Backdrop {
    public CustomBackdrop (BinaryPacker.Element data)
        : base() {
        int valueA = data.AttrInt("a", defaultValue: 3);
        bool valueB = data.AttrBool("a");
        // etc...
    }

    public override void Update(Scene scene) { ... }
    public override void Render(Scene scene) { ... }
}
```

Similarly to custom entities, instead of having a constructor which takes in a `BinaryPacker.Element`, you can have a static method which takes it in, and returns a `Backdrop`. By default, the method's name must be `Load`, but it can be changed by appending `=Name` at the end of the custom backdrop ID to set it to `Name`, for instance.

```cs
[CustomBackdrop("CustomBackdrops/Test=CreateBackdrop")]
public class CustomBackdrop : Backdrop {
    // ...
    public static Backdrop CreateBackdrop(BinaryPacker.Element data) => new();
}
```

Closes #461.

2022-07-05 01:17 UTC, microlith57 requested changes

2022-07-05 01:17 UTC, microlith57 commented on Celeste.Mod.mm/Mod/Everest/Everest.cs
> +
whitespace :despair:

2022-07-05 02:02 UTC, catapillie commented on Celeste.Mod.mm/Mod/Everest/Everest.cs
> +
my bad, fixed.

2022-07-07 16:57 UTC, coloursofnoise reviewed
Should the `CustomBackdropAttribute` file be lumped into the `Entities` folder instead of in its own? Currently that folder is a bit of a catch-all, including renderers and cutscenes.

2022-07-07 17:51 UTC, catapillie commented
I wouldn't mind doing so. The reason I didn't is that everything in the `Entities` folder is related to entities in some way, most of the files being entities themselves, attributes for custom entity stuff, and there's like one component.

2022-07-10 19:09 UTC, coloursofnoise commented
Leaving it in `Backdrops` should be fine, I would just make a note to specify the namespace in the documentation, since it differs from the other `Custom___Attribute`s

2022-07-10 19:09 UTC, merged