Add colored terminal logging support
EverestAPI/Everest pull request #664
Opened 2023-09-03 16:42 UTC by psyGamer

Adds colored terminal logging, if the terminal supports it.
The log file doesn't contain any color escape codes.

This especially helps while developing mods, because it makes non-info logs stand out.
The following colors are used, can be changed to any other ANSI color if desired:
- Verbose: Purple
- Debug: Blue
- Info: White
- Warn: Yellow
- Error: Red

There's a new CLI flag: `--color`, which controls whether to use ANSI colors in the termianl output.
- `on`: Force enable ANSI colors
- `off`: Force disable ANSI colors
- `auto`(default): Tries to enable color support on Windows and assums that termials on MacOS/Linux support colors.
While the assumption is a bit naive, there isn't really an easy way to figure it out and most terminals atleast support 4bit ANSI colors, which this is using.

Additionally there are new shorthands for logging at a specific level, since they are a nice QoL feature and it felt fitting to include them with this PR. This deprecates `Logger.Log(tag, msg)`, which seems to be quite extensivly used, but it doesn't make sense to keep using it when `Logger.Verbose(tag, msg)` exists and does the exact same thing.

If these shorthands are accepted I'd push a commit, replacing every `Logger.Log(LogLevel...` inside Everest, but havn't done so yet, to keep the diff reasonable sized.

2023-09-04 12:02 UTC, JaThePlayer reviewed
I'm quite concerned about this making logging even slower due to the double write and additional string allocations, and as such I'd like for this to be **opt-in** via an in-game setting. (since it's entirely useless for 99% of players)

2023-09-04 12:02 UTC, JaThePlayer commented on Celeste.Mod.mm/Mod/Everest/Logger.cs
> +        [Obsolete("Use Logger.Verbose instead")]
Imo it really doesn't make sense to deprecate this, as it doesn't hurt anyone to keep it around.

2023-09-04 12:08 UTC, psyGamer commented
I can add an in-game options. Should the CLI argument be removed in favour of this?

2023-09-04 12:34 UTC, psyGamer commented
I understand that most players won't use this, however I fear that those who would use it wouldn't know about it existing when it's disabled by default.
Maybe having the auto-state also check if the user has a console open would be a good idea, but IDK how this could even be implemented besides checking for `--console` on Windows. The problem with that is that it's not the only option to have a termianl open.

2023-09-04 13:11 UTC, JaThePlayer commented
Alright, checked with a profiler and it's not that much worse than before, I forgot that the double write always happened ⛄. I'm fine with it being on by default in this case, but I'm still glad it's an in-game setting though.

2023-09-04 13:15 UTC, psyGamer commented
Alright, I assume i can remove the `--color` CLI option again in that case?
Also can I push the commit for replacing `Logger.Log(LogLevel.Info, ...)` with `Logger.Info(...)` (and all other levels), since it'll kinda bloat the diff?

2023-09-04 13:21 UTC, JaThePlayer commented
Yea the CLI option can go, I can't see a use for it tbh. As for the mass-replace, I don't really mind personally, but I'm kind of worried about potential merge conflicts with the core branch with so many changes 🤔

2023-09-04 13:33 UTC, psyGamer commented
There seem to be about 240 instances, but I don't think core changes many of logs so I don't think it should be an issue.
However what should be accounted for when merging into core is replacing new log statements as well and maybe change some exception logs as well (see 816b77a)
EDIT: Also when merging into core, PlatformHelper can be replaced with RuntimeInformation.

2023-09-04 14:09 UTC, psyGamer commented
I wonder if there should be an option to customize the colors. I don't think supporting truecolor would be worth it, but maybe limiting it to 4bit ANSI colors?
However that should probably only be an option inside the settings file and not in-game, since it would just clutter the core module settings.

2023-11-18 18:37 UTC, psyGamer commented
I wonder if the `(11/18/2023 19:34:13) [Everest]` prefix should maybe be gray?

2024-08-03 14:24 UTC, maddie480 commented
Merge conflicts to fix

2024-08-03 17:37 UTC, maddie480 requested changes
Also, conflicts again :ohnoshiro:

2024-08-03 17:37 UTC, maddie480 commented on Celeste.Mod.mm/Mod/Everest/Everest.cs
> +                Logger.Error("core", "Failed to enalbe Windows VT support!");
enable* :suspicioushiro:

2024-08-03 17:37 UTC, maddie480 commented on Celeste.Mod.mm/Mod/Core/CoreModuleSettings.cs
> +        private bool _ColorizedLogging = true;
Are we OK with this being opt-_out_? 🤔

2024-08-03 17:37 UTC, maddie480 commented on Celeste.Mod.mm/Mod/Core/CoreModuleSettings.cs
> +                    Logger.Error("core", "Failed to enalbe Windows VT support!");
enable* again

2024-08-03 17:48 UTC, maddie480 commented on Celeste.Mod.mm/Mod/Core/CoreModuleSettings.cs
> +        private bool _ColorizedLogging = true;
I got referred to a previous conversation: yes we are OK because there's no performance impact

2024-08-03 17:54 UTC, merged