Add an event to fill animtions for player
EverestAPI/Everest pull request #870
Opened 2024-12-27 13:54 UTC by AAA1459

2025-01-01 08:47 UTC, microlith57 requested changes

2025-01-01 08:47 UTC, microlith57 commented on Celeste.Mod.mm/Mod/Everest/Everest.Events.cs
> +                /// Mods using this should always add an id to <see cref="List{T}"/> ids whether what the <see cref="string"/> id was given, to avoid certain <see cref="string"/> id missing their ani
are you sure `<see cref="string"/> id` is correct? shouldn't you reference the parameter name, not its type?

2025-01-01 08:47 UTC, microlith57 commented on Celeste.Mod.mm/Mod/Everest/Everest.Events.cs
> +                /// Mods using this should always add an id to <see cref="List{T}"/> ids whether what the <see cref="string"/> id was given, to avoid certain <see cref="string"/> id missing their ani
also, i'm not sure what this description means exactly, could you provide an example minimal implementation of the expected use case?

2025-01-01 08:47 UTC, microlith57 commented on Celeste.Mod.mm/Patches/PlayerSprite.cs
> +
spurious blank line

2025-01-01 08:47 UTC, microlith57 commented on Celeste.Mod.mm/Mod/Everest/Everest.Events.cs
> +                public static HashSet<string> DoNotFillAnimFor = new(StringComparer.CurrentCultureIgnoreCase);
are you sure this should be in `Events`? also, this should be documented

2025-01-01 08:47 UTC, microlith57 commented on Celeste.Mod.mm/Mod/Everest/Everest.Events.cs
> +                public static event GetIdsUsedFillAnimForIdHandler OnGetIdsUsedFillAnimFor;
i don't like this name; please make it more descriptive. it should be "OnSomeEvent" where SomeEvent is the description of what event happened

2025-01-01 08:57 UTC, AAA1459 commented on Celeste.Mod.mm/Mod/Everest/Everest.Events.cs
> +                /// Mods using this should always add an id to <see cref="List{T}"/> ids whether what the <see cref="string"/> id was given, to avoid certain <see cref="string"/> id missing their ani
I'm not sure how to reference the parameter name of `GetIdsUsedFillAnimForIdHandler` in the description of `OnGetIdsUsedFillAnimFor`

2025-01-01 08:58 UTC, microlith57 commented on Celeste.Mod.mm/Mod/Everest/Everest.Events.cs
> +                /// Mods using this should always add an id to <see cref="List{T}"/> ids whether what the <see cref="string"/> id was given, to avoid certain <see cref="string"/> id missing their ani
hmm, fair

2025-01-01 09:01 UTC, AAA1459 commented on Celeste.Mod.mm/Mod/Everest/Everest.Events.cs
> +                public static event GetIdsUsedFillAnimForIdHandler OnGetIdsUsedFillAnimFor;
I'm not good at naming, what do you think of `GetIdsToFindAndFillAnimFor`

2025-01-01 09:09 UTC, AAA1459 commented on Celeste.Mod.mm/Mod/Everest/Everest.Events.cs
> +                public static event GetIdsUsedFillAnimForIdHandler OnGetIdsUsedFillAnimFor;
or 'FindIdsToFillAnimOfTheirFor'

2025-01-01 09:20 UTC, AAA1459 commented on Celeste.Mod.mm/Mod/Everest/Everest.Events.cs
> +                public static HashSet<string> DoNotFillAnimFor = new(StringComparer.CurrentCultureIgnoreCase);
I feel like I can't be sure if putting a delegate that pass a List in the patch class made sense, so I put it in `Events`

2025-02-02 13:08 UTC, maddie480 commented
I messed up the merge :despair: it's nearly impossible to resolve online because you "modified" the whole file (probably has to do with line endings)

2025-02-02 13:16 UTC, maddie480 commented
I force-pushed to cancel the merge, and just converted Everest.Events to Linux line endings locally, that did it for resolving the "conflict"

2025-02-03 19:35 UTC, maddie480 commented
what does "filling an animation" mean actually :thinking:

2025-02-04 01:15 UTC, AAA1459 commented
> what does "filling an animation" mean actually 🤔

where is it

2025-02-21 11:41 UTC, AAA1459 commented on Celeste.Mod.mm/Mod/Everest/Everest.Events.cs
> +                public static event GetIdsUsedFillAnimForIdHandler OnGetIdsUsedFillAnimFor;
now its `FindHelperPlayerAnimSet` etc, hope its good

2025-11-29 01:19 UTC, SnipUndercover requested changes
Both files show as if they have been changed completely, likely due to line endings.
Please avoid doing that as it makes changes difficult to understand and messes up the `git blame`.

2025-11-29 01:41 UTC, closed without merging